# Generated by Django 5.2.12 on 2026-04-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_kb_chunks_and_citations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="knowledgebase",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Knowledge Bases"},
        ),
        migrations.RemoveIndex(
            model_name="knowledgebase",
            name="kb_user_created_idx",
        ),
    ]
