# Generated by Django 5.2.12 on 2026-04-21 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_knowledgebase_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='course',
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['user', 'title']},
        ),
        migrations.AddField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
