# Generated by Django 5.2.12 on 2026-04-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_topic_course_alter_topic_options_topic_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='source_type',
            field=models.CharField(choices=[('none', 'None'), ('web', 'Web')], default='none', max_length=20),
        ),
        migrations.DeleteModel(
            name='KnowledgeBaseChunk',
        ),
        migrations.DeleteModel(
            name='KnowledgeBase',
        ),
    ]
